title: Nexly Network
description: >-
  The Nexly Network is home to nostalgic minigames.
url: "https://nexly.network"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /post/:title